[package]
name = "rust-eze-tomtom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
robotics_lib = { git = "ssh://git@github.com/Advanced-Programming-2023/Robotic-Lib.git", branch = "master" }